### ISSUE TITLE
Changes not updating on website

### ISSUE THREAD

**Issue by lottiegasp** [langcog/metalab#26]
I have tried to 1) add new levels to columns by editing spec.yaml, and 2) add the language-discrimination dataset, but I am not seeing these changes updating on the website. Namely 1) when I try to use the data validator with the language-discrimination URL, it still tells me the dependent_measure column is not validated, and when I check dependent_measure under "Fields information" I can see that the new levels I added are not there yet. And the language-discrimination dataset is not showing up under "Datasets by domain".

Am I missing some steps?

**Comment by erikriverson** [comment]
Hey @lottiegasp! 

I am looking into this, one thing I can think of is the way the site is currently setup, we need to run this command https://github.com/langcog/metalab#updating-to-latest-data-optional locally when the datasets are updated. That will update the CSV and Rdata files in this directory, which you can then commit and will be used by the site when it's built: https://github.com/langcog/metalab/tree/main/shinyapps/site_data/csv . Can you confirm if that step was run? That may explain why the data wasn't showing up.

**Comment by erikriverson** [comment]
For the other issue involving the validator behavior, that one is my mistake. When the new site was being developed, I had temporarily commented out the deployment to the Shiny server so that we didn't overwrite the existing apps with the development version. Now that it's live, I will uncomment that part out. Will followup shortly when that's done.

**Comment by erikriverson** [comment]
Hey @lottiegasp , the issue with the validator should be fixed now. Please try it out when you can. To get the language discrimination dataset to show up under the domain, try this command locally, which will update all the data in the repository, then commit: https://github.com/langcog/metalab#updating-to-latest-data-optional

Thank you for the report!

**Comment by lottiegasp** [comment]
Hi Erik,

Unfortunately the Data validator still shows false for dependent_measure, and the new levels in dependent_measure don't show up in Fields information.

I didn't know about that last step of running source(here::here("build", "update-metalab-data.R")), so that's good to know. When I run it I get the following message:
_Dataset 'Language discrimination and preference' has invalid value 'reaction_time' for field 'dependent_measure'.
Dataset 'Language discrimination and preference' has invalid value 'number_sucks' for field 'dependent_measure'.
Dataset 'Language discrimination and preference' has invalid value 'trials_triggered' for field 'dependent_measure'.
Dataset 'Language discrimination and preference' has invalid value 'sucking_rate' for field 'dependent_measure'.
Dataset 'Language discrimination and preference' has invalid value 'peak_latency' for field 'dependent_measure'._
which suggests that it will be fixed when the data validator issue is fixed. Let me know if I can do something to help with this. Thanks!

**Comment by erikriverson** [comment]
Got it! This is fixed now and deployed. It was an issue that the metalabr package was still reading the metadata from the previous metalab2 repository. The site now has the new dataset that you added, thank you!

**Comment by lottiegasp** [comment]
Hi @erikriverson, not sure if the issue is related, but I am having problems again getting the new datasets to appear on the website. When I run that line of code in RStudio I get the following error messages, and can't interpret them, can you help me?

source(here::here("build", "update-metalab-data.R"))

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

here() starts at C:/Users/loret/OneDrive/Documents/Work/MetaLab/metalab
Error: Internal error in `vec_proxy_assign_opts()`: `proxy` of type `character` incompatible with `value` proxy of type `NULL`.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Internal error in `vec_proxy_assign_opts()`: `proxy` of type `character` incompatible with `value` proxy of type `NULL`.
Backtrace:
 1. base::source(here::here("build", "update-metalab-data.R"))
 5. metalabr::get_metalab_dataset_info(here("metadata", "datasets.yaml")) build/update-metalab-data.R:9:0
 6. dplyr::bind_rows(datasets)
 7. vctrs::vec_rbind(!!!dots, .names_to = .id)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Internal error in `vec_proxy_assign_opts()`: `proxy` of type `character` incompatible with `value` proxy of type `NULL`.
Backtrace:
    x
 1. +-base::source(here::here("build", "update-metalab-data.R"))
 2. | +-base::withVisible(eval(ei, envir))
 3. | \-base::eval(ei, envir)
 4. |   \-base::eval(ei, envir)
 5. \-metalabr::get_metalab_dataset_info(here("metadata", "datasets.yaml")) build/update-metalab-data.R:9:0
 6.   \-dplyr::bind_rows(datasets)
 7.     \-vctrs::vec_rbind(!!!dots, .names_to = .id)
 8.       \-(function () ...

**Comment by christinabergmann** [comment]
Is this related to #46 ?

**Comment by lottiegasp** [comment]
@erikriverson Now that #46 is resolved, I get a different error message when running this code in RStudio:

> source(here::here("build", "update-metalab-data.R"))
Error in get_metalab_data(dataset_yaml, field_info = field_info) : 
  unused argument (field_info = field_info)

**Comment by erikriverson** [comment]
@lottiegasp , thank you for reporting that. Can you please paste the output of this command before running the `install_github` command below, which should fix it? 

```
renv::status()
```

To fix the issue,  you can update the metalabr package, with 
```
devtools::install_github("langcog/metalabr")
```
I'll try to think of a way to alert users when a new version of the package is required. If you don't yet have the `devtools` package, you can `install.packages('devtools')`

**Comment by lottiegasp** [comment]
@erikriverson here is the output

> renv::status()
The following package(s) are no longer used in this project:
              _
  fs            [1.5.0]
  gargle        [r-lib/gargle@retry]
  googledrive   [1.0.1]
  uuid          [0.1-4]

Use `renv::snapshot()` to remove them from the lockfile.

I was also prompted to install Rtools40 in order to install metalabr, do we perhaps want to make that clearer in the instructions for people?

But otherwise, it worked, thanks for your help!
